# Generated by Django 2.2.7 on 2019-11-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('couverture', models.URLField()),
                ('categorie', models.CharField(max_length=50)),
                ('gameplay', models.URLField()),
                ('prix', models.IntegerField()),
            ],
        ),
    ]
