# Generated by Django 4.1.3 on 2022-11-07 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Application', '0002_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='couverture',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameplay',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
