# Generated by Django 4.1.3 on 2022-11-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_game_couverture_alter_game_gameplay_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='username',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='ranking',
            old_name='score',
            new_name='max_score',
        ),
    ]
