# Generated by Django 4.1.3 on 2022-11-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_rename_username_ranking_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='max_score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='ranking',
            old_name='email',
            new_name='username',
        ),
    ]
