# Generated by Django 4.1.3 on 2022-11-09 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Application', '0005_rename_max_score_ranking_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='username',
        ),
        migrations.AlterField(
            model_name='ranking',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
