# Generated by Django 4.1.3 on 2022-11-09 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Application', '0007_alter_ranking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
