# Generated by Django 4.1.3 on 2022-11-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_alter_ranking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='id',
            new_name='user',
        ),
    ]
